### ISSUE TITLE
adhérents

### ISSUE THREAD

**Issue by rodseb** [ptibogxiv/adherentsplus#1]
bonjour 
j'ai plusieurs erreur les voici
merci de la proposition du module 

## sur la fiche de l'adherent

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20171213220314
Dolibarr: 6.0.4
Niveau de fonctionnalités: 0
PHP: 7.0.26
Server: Apache
OS: Linux multijeux 2.6.32-042stab123.1 #1 SMP Wed Mar 22 15:21:30 MSK 2017 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

Url sollicitée: /custom/adherentsplus/card.php?rowid=1
Referer: https://asso.spm-corp.fr/custom/adherentsplus/index.php?idmenu=38&mainmenu=adherentsplus&leftmenu=
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT c.rowid, c.fk_adherent, c.subscription, c.note, c.fk_bank, c.fk_type, c.tms as datem, c.datec as datec, c.dateadh as dateh, c.datef as datef FROM Lox_subscription as c WHERE c.fk_adherent = 1 ORDER BY c.dateadh DESC
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'c.fk_type' in 'field list'

Message: Unknown column 'c.fk_type' in 'field list' sql=SELECT c.rowid, c.fk_adherent, c.subscription, c.note, c.fk_bank, c.fk_type, c.tms as datem, c.datec as datec, c.dateadh as dateh, c.datef as datef FROM Lox_subscription as c WHERE c.fk_adherent = 1 ORDER BY c.dateadh DESC

## sur la fiche du type d'adherent

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20171213215424
Dolibarr: 6.0.4
Niveau de fonctionnalités: 0
PHP: 7.0.26
Server: Apache
OS: Linux multijeux 2.6.32-042stab123.1 #1 SMP Wed Mar 22 15:21:30 MSK 2017 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

Url sollicitée: /custom/adherentsplus/type.php?rowid=3
Referer: https://asso.spm-corp.fr/custom/adherentsplus/index.php?idmenu=38&mainmenu=adherentsplus&leftmenu=
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT d.rowid, d.login, d.firstname, d.lastname, d.societe, d.datefin, d.email, d.fk_adherent_type as type_id, d.morphy, d.statut, t.libelle as type, t.subscription FROM Lox_adherent as d, Lox_adherent_type as t WHERE d.fk_adherent_type = t.rowid AND d.entity IN (1) AND t.rowid =
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20171213215424
Dolibarr: 6.0.4
Niveau de fonctionnalités: 0
PHP: 7.0.26
Server: Apache
OS: Linux multijeux 2.6.32-042stab123.1 #1 SMP Wed Mar 22 15:21:30 MSK 2017 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

Url sollicitée: /custom/adherentsplus/type.php?rowid=3
Referer: https://asso.spm-corp.fr/custom/adherentsplus/index.php?idmenu=38&mainmenu=adherentsplus&leftmenu=
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT d.rowid, d.login, d.firstname, d.lastname, d.societe, d.datefin, d.email, d.fk_adherent_type as type_id, d.morphy, d.statut, t.libelle as type, t.subscription FROM Lox_adherent as d, Lox_adherent_type as t WHERE d.fk_adherent_type = t.rowid AND d.entity IN (1) AND t.rowid = ORDER BY d.lastname DESC LIMIT 26
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY d.lastname DESC LIMIT 26' at line 1

## sur la liste des Types d'adhérents

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20171213213941
Dolibarr: 6.0.4
Niveau de fonctionnalités: 0
PHP: 7.0.26
Server: Apache
OS: Linux multijeux 2.6.32-042stab123.1 #1 SMP Wed Mar 22 15:21:30 MSK 2017 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

Url sollicitée: /custom/adherentsplus/type.php?idmenu=36&mainmenu=adherentsplus&leftmenu=
Referer: https://asso.spm-corp.fr/custom/adherentsplus/type.php?idmenu=36&mainmenu=adherentsplus&leftmenu=
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT d.rowid, d.libelle as label, d.subscription, d.vote, d.welcome, d.price, d.vote, d.automatic FROM Lox_adherent_type as d WHERE d.entity IN (1)
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'd.welcome' in 'field list'

**Comment by ptibogxiv** [comment]
Bonjour,

En effet les modifications de la base ne sont pas encore incluses. C'est prévu prochainement

Il vous faut ajouter les champs suivants dans la base de données:
dans llx_adherent_type
  `welcome` double(24,8) DEFAULT '0.00000000',
  `price` double(24,8) DEFAULT '0.00000000',
  `price_level` int(11) DEFAULT NULL,
  `vote` varchar(3) DEFAULT NULL,
  `automatic` varchar(3) DEFAULT NULL,

dans llx_subscription
  `fk_type` int(11) DEFAULT NULL,

**Comment by rodseb** [comment]
merci
