### ISSUE TITLE
api

### ISSUE THREAD

**Issue by Thipas** [ptibogxiv/adherentsplus#10]
bonjour ptibogxiv
j 'ai installé la branche master sur une version 9 de dolibarr
api rest "/api/index.php/adherentsplus?sortfield=t.rowid&sortorder=ASC"
me retourne 
[
  {
    "mesgs": null,
    "login": null,
    "ref": null,
    "pass": null,
    "pass_indatabase": null,
    "pass_indatabase_crypted": null,
    "societe": null,
   .... 
jusqu'a la fin sur tous les enregistrements
sur 
/api/index.php/adherentsplus/"id" existant
{
  "error": {
    "code": 401,
    "message": "Unauthorized: Access not allowed for login admin"
  },
  "debug": {
    "source": "api_adherentsplus.class.php:72 at call stage",
    "stages": {
      "success": [
        "get",
        "route",
        "negotiate",
        "authenticate",
        "validate"
      ],
      "failure": [
        "call",
        "message"
      ]
    }
  }
}
les droits sont ok dans dolibarr
une idee ?

**Comment by ptibogxiv** [comment]
Bonjour,

Cela semble être un problème de droits. Il faut que  en parallèle le plugin adhérent natif soit installé et que les droits de gestion de l'adhérents soit données à l'utilisateur de l'API

Attention,  la branche master est en train de passer sur le v10, j'ai créé une branche v9 ou utiliser les release de la bonne branche de dolibarr.

**Comment by Thipas** [comment]
Merci de ta réponse je vais mettre a jour avec l'autre branche
petit UP pour la update de la base, 
dans /core/module/modAdherentsPlus.class.php en fin de fichier avant le dernier `}`
puis cree le rep "sql"
et un fichier data.sql avec les update

```
private function loadTables()
	{
		return $this->_load_tables('/adherentsplus/sql/');
}
```

**Comment by Thipas** [comment]
le fichier data
[data.zip](https://github.com/ptibogxiv/adherentsplus/files/3028481/data.zip)

**Comment by Thipas** [comment]
cela évitera les questions sur le forum et pratique si pas d’accès au sql direct

**Comment by ptibogxiv** [comment]
intégré ds la branche master
