### ISSUE TITLE
EXTRAFIELDS

### ISSUE THREAD

**Issue by Thipas** [ptibogxiv/adherentsplus#11]
Bonjour
je pense qu'il s’agit d'un bug déjà présent sur adhérent d'origine vu mes tests
le constat:
sur les API , lors d'un POST ou un PUT , les extrafield sont pris en compte jusqu'au n-1
pour contourner le pb j'ai crée un extrafield de plus invisible que je passe dans le json

**Comment by ptibogxiv** [comment]
@Thipas  je ne rencontre pas ce problème. tout mes extrafields se synchronise.  cela est peut être lié au type de votre n-1 qui rencontre un problème de codage (ex balise de fin pas bonne)

**Comment by Thipas** [comment]
Ok je vais vérifier ça
