### ISSUE TITLE
Erreur php supprésion adhérents par lot

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/adherentsplus#12]
Bonjour, 

L'action suivante retourne l'erreur php ci-après : 

- Dolibarr > adhérents+ > Liste > 
- Sélectioner plusieurs adhérents via case à coché à droite
- Sélectioner l'action "supprimer" dans le menu déroulant en haut
- Confirmer la superssion "en masse"

Fatal error: Uncaught Error: Class 'Adherent' not found in /var/www/clients/client1/web7/web/dolibarr/htdocs/core/actions_massactions.inc.php:1145 Stack trace: #0 /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/list.php(211): include() #1 {main} thrown in /var/www/clients/client1/web7/web/dolibarr/htdocs/core/actions_massactions.inc.php on line 1145

PHP7.2
Dolibarr 9.0.2
Adhérent+ 9.01

**Comment by ptibogxiv** [comment]
fixed !
