### ISSUE TITLE
Impossible d'envoyer des email

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/adherentsplus#14]
Bonjour

php7.2
Dolibarr 9.0.2
Adhérents+ 9.01

impossible d'envoyer des email depuis adhérent+

process 
adhérent/+ > fiche adhérent > envoyer email > envoyer un email

quand l'envoi d'email marche, tel que c'est le cad depuis le module adhérent, un cartouche de notification vert nous informe que l'email à été accepté pour l'envoi.

Dans adhérent+, ce cartouche vert ne s'affiche pas, et le mail n'est pas envoyé (en tout cas pas reçu)

Par conséquent, lorsque l'on utilise doliconnect, tout les emails d'inscription/validation qui devrait entre envoyé ne le sont pas.

**Comment by ptibogxiv** [comment]
on atteint les limites de adherentsplus. bug lié a dolibarr età l'implementation des emails.. à reflechir comment le resoudre....

**Comment by Kwagga-Quagga** [comment]
ok.

**Question quasi rhétorique** : si adhérents+ est construit à partir d'adhérents, mais en y ajoutant des fonctionalité, qu'est ce qui dans adhérents+ casse la fonctionalité d'envoir d'email depuis le module ?

**Question pas du tout rhérorique** : sur une instance fonctionnant avec d'adhérents+ et doliconnect, et ou les comptes utilisateur-wp, tiers-dolibarr et adhérents dolibarr sont créés depuis doliconnect, comment faire pour que les utilisateur (sensus usager ou clients du site) qui créent leur compte, ou adhérent à l'association via dolibarr reçoivent les emails de confirmation ? 


Du coup, grosse grosse question.

**Comment by ptibogxiv** [comment]
Pour le 1.. Pb de "translation" de fonction et renommage.

Pour le 2... Configurer les emails par défauts dans l'admin de dolibarr

**Comment by Kwagga-Quagga** [comment]
> Pour le 1.. Pb de "translation" de fonction et renommage.
> 

**ok question quasi rhétorique** (pour comprendre) : tu veux dire que adhérents+ ne contient pas le code d'adhérents, mais se présente comme une surcouche, et lorsque qu'ahdérent+ appelle la fonction maol de ahérants il y a un problème de "translation" et de renommage de l'un à lautre ? 


> Pour le 2... Configurer les emails par défauts dans l'admin de dolibarr

**question, problème pas du tout rhétorique** :ça marche pas chez moi...
dolibarr >  configuration > email > ça marche
dolibarr > outils > mailing > ça marche
dolibarr > adhérents > fiche adhérent > envoyer email > ça marche
dolibar > tiers > fiche tiers > envoyer email > ça marche
dolibarr > commercial > comande/proposition commerciale > fiche > envoyer email > ça marche
dolibarr > facture > facture xx > envoyer email > ça marche

doliconnect > creation de compte > wp envoi bien un email 
doliconnecrt > adhésion > pas de mail envoyé (en tout cas pas reçu, même pas en spam)

**Comment by ptibogxiv** [comment]
oui care certaines focntions ne peuvent focntion sans adhérent ni sans tiers... pb de codage natif du core... et le module n'a pas vocation à survivre au long cours.... c'est en attente d'intégration dans le core.

pour les emails... c'est encour... la v9 a changer la façon de procéder et je répéte que si tu n'a pas configuer les emails par défaut pour les actions adhérents.. tu ne recevras rien. cf dolibarr

**Comment by Kwagga-Quagga** [comment]
> pour les emails... c'est encour... la v9 a changer la façon de procéder et je répéte que si tu n'a pas configuer les emails par défaut pour les actions adhérents.. tu ne recevras rien. cf dolibarr


Oui, alors soit il y a un problème, soit quelque chose m'échappe mais 
dolibarr > configuration > module > adhérents >  configuration > forulaire d'auto inscription > saisue du forulaire > email envoyé
 - un email accusé de récépetion  à l'adresse saisie dans le formulaire
 - un email d'information à l'adresse saisie dans la configuration de adhérent(+)>email


dolibarr > adhérent > module > fiche adhérent (celui saisi ci-dessus) > valider > email envoyé 
 - un email de bienvenue à l'adresse de l'adhérent (donc saisie dans le formulaire)
 - un email d'information à l'adresse saisie dans la configuration de adhérent(+)>email


avec la même configuration de dolibarr, si je créé un adhérent depuis doliconnect, aucun de ses emails ne sont envoyé.

peut être j'ai quelque chose de mal configuré dans doliconnect, ou dans adhérent+, mais je ne vois pas où

**Comment by ptibogxiv** [comment]
le pb est le changement en cours sur cette page 
https://mon domaine/adherents/admin/adherent_emails.php
 
et non repris en v9

https://mondomain/custom/adherentsplus/admin/adherent_emails.php

ça sera corrigé en v10

**Comment by Kwagga-Quagga** [comment]
> le pb est le changement en cours sur cette page
> https://mon domaine/adherents/admin/adherent_emails.php
> 
> et non repris en v9
> 
> https://mondomain/custom/adherentsplus/admin/adherent_emails.php
> 
> ça sera corrigé en v10
> 
> dolibarr utilise maintenant des masque de mail à paramètrer et non plus des formulaire texte prérempli

autrement dit : 
 1. il est impossible d'envoyer de mails depuis adhérents+ ; pour l'heure, et si je comprends bien jusqu'à la v10 de dolibar
2. les adhésions souscrites depuis doliconnect ne peuvent bénéficier des fonctionalité lié à l'envoi automatique d'email de confirmation ou de bienvenu ; pour l'heure, et si je comprends bien jusqu'à la V10 de dolibarr

c'est bien ça ? 

autrement, quel est le workflow ou le walkaround du moment  ?

merci

**Comment by ptibogxiv** [comment]
email auto suite au workflow en cours... pour le moment v10 puis downgrade

**Comment by ptibogxiv** [comment]
réglé dans la v10 avec meilleur code au sein du plugin natif pour integration des 2 modules adhérents en 1
