### ISSUE TITLE
Erreur formulaire d'auto inscription

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/adherentsplus#16]
php 7.2
dolibarr 9.0.2
adhérent+ 9.0.1

la page du formulaire d'auto inscription présente cette série de warnings : 

Type * | Warning:  Use of undefined constant note - assumed 'note' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 338  Warning:  Use of undefined constant label - assumed 'label' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 339  Warning:  Use of undefined constant price - assumed 'price' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 340  Warning:  Use of undefined constant welcome - assumed 'welcome' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 341  Warning:  Use of undefined constant automatic - assumed 'automatic' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 342  Warning:  Use of undefined constant automatic_renew - assumed  'automatic_renew' (this will throw an Error in a future version of PHP)  in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 343  Warning:  Use of undefined constant use_default - assumed 'use_default' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 344  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 345  Warning:  Use of undefined constant note - assumed 'note' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 338  Warning:  Use of undefined constant label - assumed 'label' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 339  Warning:  Use of undefined constant price - assumed 'price' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 340  Warning:  Use of undefined constant welcome - assumed 'welcome' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 341  Warning:  Use of undefined constant automatic - assumed 'automatic' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 342  Warning:  Use of undefined constant automatic_renew - assumed  'automatic_renew' (this will throw an Error in a future version of PHP)  in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 343  Warning:  Use of undefined constant use_default - assumed 'use_default' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 344  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 345  Warning:  Use of undefined constant note - assumed 'note' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 338  Warning:  Use of undefined constant label - assumed 'label' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 339  Warning:  Use of undefined constant price - assumed 'price' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 340  Warning:  Use of undefined constant welcome - assumed 'welcome' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 341  Warning:  Use of undefined constant automatic - assumed 'automatic' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 342  Warning:  Use of undefined constant automatic_renew - assumed  'automatic_renew' (this will throw an Error in a future version of PHP)  in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 343  Warning:  Use of undefined constant use_default - assumed 'use_default' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 344  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/class/adherent_type.class.php on line 345  Warning:  Use of undefined constant price - assumed 'price' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 539  Warning:  Use of undefined constant welcome - assumed 'welcome' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 544  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 545  Warning:  Use of undefined constant automatic - assumed 'automatic' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 546  Warning:  Use of undefined constant label - assumed 'label' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 547 > Membre d'honneur Warning:  Use of undefined constant note - assumed 'note' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 548  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 551  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 551  Warning:  Use of undefined constant price - assumed 'price' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 539  Warning:  Use of undefined constant welcome - assumed 'welcome' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 544  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 545  Warning:  Use of undefined constant automatic - assumed 'automatic' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 546  Warning:  Use of undefined constant label - assumed 'label' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 547 > Membre Bienfaiteur Warning:  Use of undefined constant note - assumed 'note' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 548  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 551  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 551  Warning:  Use of undefined constant price - assumed 'price' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 539  Warning:  Use of undefined constant welcome - assumed 'welcome' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 544  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 545  Warning:  Use of undefined constant automatic - assumed 'automatic' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 546  Warning:  Use of undefined constant label - assumed 'label' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 547 > Membre actif Warning:  Use of undefined constant note - assumed 'note' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 548  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 551  Warning:  Use of undefined constant rowid - assumed 'rowid' (this will throw an Error in a future version of PHP) in /var/www/clients/client1/web7/web/dolibarr/htdocs/custom/adherentsplus/public/new.php on line 551
-- | --

**Comment by ptibogxiv** [comment]
default public page in adherentsplus end... -> merge in progress with default page. Too much bug in this page
