### ISSUE TITLE
Validation auto-inscription :  erreur (aléatoire ?)

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/adherentsplus#17]
PHP 7.2
Dolibarr 9.0.2
adhérent+ 9.0.1

le formulaire d'autoinscription proposé par adhérent+ prénsente une série de message d'erreur (voir #16 )

Ainsi ce test est basé sur l'usage du formulaire d'inscription d'adhérents

Dolibarr > configuration > modules > adhérent > configuration > formulaure d'auto inscription > saisi du formulaire d'auto inscription > tout va bien

dolibarr > adhérent+ > fiche adhérents (celui qui vient de saisir le formulaire) > valider > erreur 

je ne sais pas si l'erreur est aléatoire, mais je l'ai eu une fois et pas une autre.

**Comment by ptibogxiv** [comment]
page supprimée -> utilisé la page auto subscription du module natif ou doliconnect
