### ISSUE TITLE
Lien "type d'adhésion" et "échéance cotisation" : amélioration workflow ?

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/adherentsplus#18]
Bonjour, 

Le module adhérents+ fait il le lien entre le "type d'adhésion" sélectionné dans les paramètres du module et la cotisation de l'adhérent  ?

Je pose cette question car je m'étonne d'un comportement, pas délétaire, mais contre intuitif.

CAS D'USAGE

dolibarr > module application > paraètres adhérent+ > type d'adhésion > choisit annuel à date fixe 
puis 
dolibarr > module application > paraètres adhérent+ > mois de débit d'exercice > Janvier

![Capture du 2019-08-25 11-57-22](https://user-images.githubusercontent.com/49561217/63648417-e4f28480-c72f-11e9-9074-c2de82b3f472.png)

Sauf erreur de ma part, 
 - les adhésions sont basées sur les années civiles du  01/01/XX au 31/12/XX
 - quel que soit la data d'adhésion, le membre est adhérent pour l'année civile en cours

____

Maintenant, 

une personne crée et paye son adhésion depuis doliconnect 

Il faut créer la cotisation dans dolibarr

Le formulaire de création de cotisation contient une date d'adhésion et une date de fin d'adhésion.
La date d'adhésion est le premier du mois en cours, mais la date de fin d'adhésion est un an plus tard, et non au 31/12 de l'année en cours.
par exemple, nous sommes le 25/08/2019, la date d'adhésion est le 01/08/2019 et la date de fin le 31/07/2020.
Logiquement, vu que les adhésions comptent pour les années civiles, la date de fin d'adhésion devrait être le 31/12/2019.
![Capture du 2019-08-25 11-58-06](https://user-images.githubusercontent.com/49561217/63648422-ecb22900-c72f-11e9-8896-0b645ef33ccf.png)

---

J'epsère avoir été compréhenssible
Cordialement

**Comment by ptibogxiv** [comment]
Si possible moins de texte et plus de capture d'ecran pour me faire gagner du temps sur le workflow posant pb.

**Comment by ptibogxiv** [comment]
la réponse est donc ds les images... pas de compte bancaire de paramètrer donc pas d'utomatisation possible et/ou plantage.
![image](https://user-images.githubusercontent.com/3135833/63683876-d83b6280-c7fb-11e9-9417-3e72a3f99715.png)
pour les dates j'ai remarqué et c'est en cours d'investigations pour ce plantage selon certains cas

**Comment by Kwagga-Quagga** [comment]
Ok, 
Je ne comprends pas trop, car je ne vois pas le lien entre l'existence d'un compte bancaire et les dates de fin d'adhésion

**Comment by ptibogxiv** [comment]
Tout simplement pcq l'écriture se crée au classement paye de la facture. Si pas de compte, pas de classement, pas d'écriture..
