### ISSUE TITLE
Problème sur paramètre du type de cotisation

### ISSUE THREAD

**Issue by ocarette** [ptibogxiv/adherentsplus#21]
Bonjour,
Le rowid n’apparait pas dans l'adresse lors du clique sur modifier. J'ai modifier le fichier en transformant $objet->id en $rowid.
J'arrive bien sur le formulaire. Par contre lorsque je valide, le rowid disparait également.
Lorsqu'avec firefox je visualise le code source, l'adresse apparait bien dans la balise form.
Ceci bloque donc la mise à jour de la fiche.
Merci pour ta réponse.

**Comment by ptibogxiv** [comment]
Bonjour quel version avez-vous ?

Si vous mettez la derniere version cela devrez focntionner (en oubliant pas de desactiver puis reactiver le module)

**Comment by ocarette** [comment]
Bonjour,
C’est la version téléchargée sur github hier quelques heures avant le message.
Pour Dolibarr, c’est la version a jour téléchargea le sur le site et j’ai installé doliconnector pour une liaison sur un site WordPress.
Olivier

Envoyé de mon iPad

**Comment by ptibogxiv** [comment]
pouvez vous faire des captures d'ecran ou faire un test ici car c'est la derniere version (correspondant au github)

https://dolidemo.ptibogxiv.net

attention la version doit etre strictement celle de votre dolibarr ( il ne faut pas télécharger les version de develop mais celle ici https://github.com/ptibogxiv/adherentsplus/releases)

**Comment by ocarette** [comment]
En effet, j'ai téléchargé la version sur releases et le système fonctionne.
