### ISSUE TITLE
Error instaling the module

### ISSUE THREAD

**Issue by DATUC** [ptibogxiv/adherentsplus#29]
Hi actualy not abel to install ur module on Dolibarr V 16.0.3 need help

![image](https://user-images.githubusercontent.com/26550824/213938585-7f131ab3-3286-4cf4-a098-1bd9a4fe464f.png)

**Comment by ptibogxiv** [comment]
Hi

Please unzip the zip and install it in the custom directory or change the name with just adherentsplus.

Dolibarr don't support several "." in file name
