### ISSUE TITLE
Erreur php

### ISSUE THREAD

**Issue by rodseb** [ptibogxiv/adherentsplus#3]
Bonjour/Bonsoir

j'ai une erreur en essayent allez sur le suivi d'une cotisation
voici l'erreur

Warning: require_once(/var/www/vhosts/***/htdocs/adherentsex/class/adherent.class.php): failed to open stream: No such file or directory in /var/www/vhosts/****/htdocs/custom/adherentsplus/subscription/info.php on line 46

Fatal error: require_once(): Failed opening required '/var/www/vhosts/spm-corp.fr/****/htdocs/adherentsex/class/adherent.class.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/*****/htdocs/custom/adherentsplus/subscription/info.php on line 46

**Comment by ptibogxiv** [comment]
correction faite
