### ISSUE TITLE
Send the confirmation of subscription to a wrong member

### ISSUE THREAD

**Issue by aureleduda** [ptibogxiv/adherentsplus#33]
The lines 388-390 causes the memberid is null, so the program send the confirmation email to the member with the smallest rowid (or ref I have no checked)
Removing this three lines resolve this, sending to the correct member.

https://github.com/ptibogxiv/adherentsplus/blob/e7f764c06ab15256dadc332d0ec55b14042bf8eb/subscription.php#L388C1-L390C30

**Comment by ptibogxiv** [comment]
fixed
