### ISSUE TITLE
Configuration impossible

### ISSUE THREAD

**Issue by d1h8offcb** [ptibogxiv/adherentsplus#35]
Bonjour,
Je viens d'installer le module adhéentsplus et quand j'essaye de le configurer j'ai ce message
404 Not Found
The server can not find the requested page:
adherant.a.fr/adherentsplus/admin/adherent.php?save_lastsearch_values=1&backtopage=%2Fadmin%2Fmodules.php (port 443)

Merci pour votre aide

**Comment by ptibogxiv** [comment]
Bonsoir,

Le module, comme tous les autres ne doit s'installer que dans le répertoire custom de Dolibarr.

Bien cordialement,

**Comment by d1h8offcb** [comment]
Merci pour votre réponse rapide!
A oui j'étais allé trop vite
Suppression et déplacement du module au bon endroit et toujours le même message

**Comment by ptibogxiv** [comment]
Le nom du dossier ne doit être que adherentsplus

**Comment by d1h8offcb** [comment]
Super ça marche
Merci beaucoup pour la réctivité!
y'a plus qu'à  tester
