### ISSUE TITLE
d.fk_parent

### ISSUE THREAD

**Issue by rodseb** [ptibogxiv/adherentsplus#4]
Bonjour 
merci de votre travail que vous avez fait 
merci encore 

vous avez oublié de rajouté a propos de la colonne " d.fk_parent " dans le  README.md

**Comment by ptibogxiv** [comment]
en effet je ne l'ai pas encore mentionné car travail en cours  mais c'est une nouvelle colonne pour la gestion adhésion de groupe. N'hésitez pas à faire une suggestions ou autres debugs
