### ISSUE TITLE
Consommations

### ISSUE THREAD

**Issue by baaaat** [ptibogxiv/adherentsplus#8]
Bonjour, que prend en compte la fonction consommation ? Affiche t'elle les produits facturés à un tiers/adhérent ?

**Comment by ptibogxiv** [comment]
l'onglet consommation est en cours de developpement. Il sert à rajouter des produits supplémentaires à facturer lors de la prochaine échéance de cotisation. ex un abonnement mensuel à un service avec en plus des consommables facturé au mois suivant
