### ISSUE TITLE
affichage extrafields dans les vues en liste

### ISSUE THREAD

**Issue by baaaat** [ptibogxiv/adherentsplus#9]
Bonjour,
J'ai un soucis d'affichage des extrafields dans les listes: même cochés (et quelque soit la visibilité choisie lors de la création de l'extrafield), pas moyen d'afficher ce fameux champ... Il est bien visible dans la vue fiche en revanche.

**Comment by ptibogxiv** [comment]
@baaaat quel est la version de dolibarr ?

**Comment by baaaat** [comment]
j'ai le même souci sur une 9.0.0 et une 8.0.2

**Comment by ptibogxiv** [comment]
@baaaat je vais regarder à ça. sans doute une partie qui n'a pas été remonté dans le code.

**Comment by ptibogxiv** [comment]
@baaaat corrigé à l'instant ;)

**Comment by baaaat** [comment]
excellent, je teste ça très vite !
